// Comprehensive Metadata for ALL DSA Algorithms across Categories with Multi-Language Code

export const ALGORITHM_CATEGORIES = [
  { id: 'sorting', name: 'Sorting Algorithms', icon: 'BarChart2' },
  { id: 'searching', name: 'Searching Algorithms', icon: 'Search' },
  { id: 'backtracking', name: 'Backtracking', icon: 'GitBranch' },
  { id: 'graphs', name: 'Graph Algorithms', icon: 'Network' },
  { id: 'trees', name: 'Tree Algorithms', icon: 'GitCommit' },
  { id: 'dp', name: 'Dynamic Programming', icon: 'Layers' },
  { id: 'greedy', name: 'Greedy Algorithms', icon: 'Zap' },
  { id: 'twoPointers', name: 'Two Pointers', icon: 'ArrowRightLeft' },
  { id: 'math', name: 'Number Theory / Math', icon: 'Calculator' }
]

export const ALGORITHMS = {
  // --- SORTING ---
  bubbleSort: {
    id: 'bubbleSort',
    name: 'Bubble Sort',
    category: 'sorting',
    description: 'Repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.',
    timeComplexity: { best: 'O(N)', average: 'O(N²)', worst: 'O(N²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function bubbleSort(arr) {', '  for (let i = 0; i < arr.length; i++) {', '    for (let j = 0; j < arr.length - i - 1; j++) {', '      if (arr[j] > arr[j + 1]) swap(arr[j], arr[j + 1]);', '    }', '  }', '}'],
      python: ['def bubble_sort(arr):', '    n = len(arr)', '    for i in range(n):', '        for j in range(0, n - i - 1):', '            if arr[j] > arr[j + 1]: arr[j], arr[j + 1] = arr[j + 1], arr[j]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'void bubbleSort(vector<int>& arr) {',
        '    int n = arr.size();',
        '    for (int i = 0; i < n - 1; i++) {',
        '        for (int j = 0; j < n - i - 1; j++) {',
        '            if (arr[j] > arr[j + 1]) swap(arr[j], arr[j + 1]);',
        '        }',
        '    }',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    bubbleSort(arr);',
        '    cout << "Sorted Array: ";',
        '    for (int x : arr) cout << x << " ";',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void bubbleSort(int[] arr) {', '    int n = arr.length;', '    for (int i = 0; i < n - 1; i++) {', '        for (int j = 0; j < n - i - 1; j++) {', '            if (arr[j] > arr[j + 1]) { int temp = arr[j]; arr[j] = arr[j+1]; arr[j+1] = temp; }', '        }', '    }', '}'],
      c: ['void bubbleSort(int arr[], int n) {', '    for (int i = 0; i < n - 1; i++) {', '        for (int j = 0; j < n - i - 1; j++) {', '            if (arr[j] > arr[j + 1]) { int temp = arr[j]; arr[j] = arr[j+1]; arr[j+1] = temp; }', '        }', '    }', '}']
    }
  },

  selectionSort: {
    id: 'selectionSort',
    name: 'Selection Sort',
    category: 'sorting',
    description: 'Divides array into sorted and unsorted region, repeatedly finding minimum element from unsorted.',
    timeComplexity: { best: 'O(N²)', average: 'O(N²)', worst: 'O(N²)' },
    spaceComplexity: 'O(1)',
    stable: false,
    code: {
      javascript: ['function selectionSort(arr) {', '  for (let i = 0; i < arr.length; i++) {', '    let minIdx = i;', '    for (let j = i + 1; j < arr.length; j++) if (arr[j] < arr[minIdx]) minIdx = j;', '    if (minIdx !== i) swap(arr[i], arr[minIdx]);', '  }', '}'],
      python: ['def selection_sort(arr):', '    for i in range(len(arr)):', '        min_idx = i', '        for j in range(i + 1, len(arr)):', '            if arr[j] < arr[min_idx]: min_idx = j', '        arr[i], arr[min_idx] = arr[min_idx], arr[i]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'void selectionSort(vector<int>& arr) {',
        '    for (size_t i = 0; i < arr.size(); i++) {',
        '        int minIdx = i;',
        '        for (size_t j = i + 1; j < arr.size(); j++) if (arr[j] < arr[minIdx]) minIdx = j;',
        '        swap(arr[i], arr[minIdx]);',
        '    }',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    selectionSort(arr);',
        '    cout << "Selection Sorted Array: ";',
        '    for (int x : arr) cout << x << " ";',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void selectionSort(int[] arr) {', '    for (int i = 0; i < arr.length; i++) {', '        int minIdx = i;', '        for (int j = i + 1; j < arr.length; j++) if (arr[j] < arr[minIdx]) minIdx = j;', '        int temp = arr[i]; arr[i] = arr[minIdx]; arr[minIdx] = temp;', '    }', '}'],
      c: ['void selectionSort(int arr[], int n) {', '    for (int i = 0; i < n; i++) {', '        int minIdx = i;', '        for (int j = i + 1; j < n; j++) if (arr[j] < arr[minIdx]) minIdx = j;', '        int temp = arr[i]; arr[i] = arr[minIdx]; arr[minIdx] = temp;', '    }', '}']
    }
  },

  insertionSort: {
    id: 'insertionSort',
    name: 'Insertion Sort',
    category: 'sorting',
    description: 'Builds final sorted array one item at a time by inserting each element into its proper position.',
    timeComplexity: { best: 'O(N)', average: 'O(N²)', worst: 'O(N²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function insertionSort(arr) {', '  for (let i = 1; i < arr.length; i++) {', '    let key = arr[i], j = i - 1;', '    while (j >= 0 && arr[j] > key) { arr[j + 1] = arr[j]; j--; }', '    arr[j + 1] = key;', '  }', '}'],
      python: ['def insertion_sort(arr):', '    for i in range(1, len(arr)):', '        key = arr[i]; j = i - 1', '        while j >= 0 and arr[j] > key: arr[j + 1] = arr[j]; j -= 1', '        arr[j + 1] = key'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'void insertionSort(vector<int>& arr) {',
        '    for (size_t i = 1; i < arr.size(); i++) {',
        '        int key = arr[i], j = (int)i - 1;',
        '        while (j >= 0 && arr[j] > key) { arr[j + 1] = arr[j]; j--; }',
        '        arr[j + 1] = key;',
        '    }',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    insertionSort(arr);',
        '    cout << "Insertion Sorted: ";',
        '    for (int x : arr) cout << x << " ";',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void insertionSort(int[] arr) {', '    for (int i = 1; i < arr.length; i++) {', '        int key = arr[i], j = i - 1;', '        while (j >= 0 && arr[j] > key) { arr[j + 1] = arr[j]; j--; }', '        arr[j + 1] = key;', '    }', '}'],
      c: ['void insertionSort(int arr[], int n) {', '    for (int i = 1; i < n; i++) {', '        int key = arr[i], j = i - 1;', '        while (j >= 0 && arr[j] > key) { arr[j + 1] = arr[j]; j--; }', '        arr[j + 1] = key;', '    }', '}']
    }
  },

  mergeSort: {
    id: 'mergeSort',
    name: 'Merge Sort',
    category: 'sorting',
    description: 'Divide and conquer algorithm dividing array into halves, sorting recursively and merging.',
    timeComplexity: { best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N log N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function mergeSort(arr, l, r) {', '  if (l >= r) return;', '  let mid = Math.floor((l + r) / 2);', '  mergeSort(arr, l, mid);', '  mergeSort(arr, mid + 1, r);', '  merge(arr, l, mid, r);', '}'],
      python: ['def merge_sort(arr):', '    if len(arr) > 1:', '        mid = len(arr) // 2', '        L, R = arr[:mid], arr[mid:]', '        merge_sort(L); merge_sort(R); merge(arr, L, R)'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'void merge(vector<int>& arr, int l, int m, int r) {',
        '    vector<int> L(arr.begin() + l, arr.begin() + m + 1);',
        '    vector<int> R(arr.begin() + m + 1, arr.begin() + r + 1);',
        '    int i = 0, j = 0, k = l;',
        '    while (i < L.size() && j < R.size()) arr[k++] = (L[i] <= R[j]) ? L[i++] : R[j++];',
        '    while (i < L.size()) arr[k++] = L[i++];',
        '    while (j < R.size()) arr[k++] = R[j++];',
        '}',
        '',
        'void mergeSort(vector<int>& arr, int l, int r) {',
        '    if (l >= r) return;', '    int mid = l + (r - l) / 2;',
        '    mergeSort(arr, l, mid); mergeSort(arr, mid + 1, r); merge(arr, l, mid, r);',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    mergeSort(arr, 0, arr.size() - 1);',
        '    cout << "Merge Sorted Array: ";',
        '    for (int x : arr) cout << x << " ";',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void mergeSort(int[] arr, int l, int r) {', '    if (l >= r) return;', '    int mid = (l + r) / 2;', '    mergeSort(arr, l, mid); mergeSort(arr, mid + 1, r); merge(arr, l, mid, r);', '}'],
      c: ['void mergeSort(int arr[], int l, int r) {', '    if (l >= r) return;', '    int mid = l + (r - l) / 2;', '    mergeSort(arr, l, mid); mergeSort(arr, mid + 1, r); merge(arr, l, mid, r);', '}']
    }
  },

  quickSort: {
    id: 'quickSort',
    name: 'Quick Sort',
    category: 'sorting',
    description: 'Picks pivot element and partitions array around pivot recursively.',
    timeComplexity: { best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N²)' },
    spaceComplexity: 'O(log N)',
    stable: false,
    code: {
      javascript: ['function quickSort(arr, low, high) {', '  if (low < high) {', '    let pi = partition(arr, low, high);', '    quickSort(arr, low, pi - 1); quickSort(arr, pi + 1, high);', '  }', '}'],
      python: ['def quick_sort(arr, low, high):', '    if low < high:', '        pi = partition(arr, low, high)', '        quick_sort(arr, low, pi - 1); quick_sort(arr, pi + 1, high)'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int partition(vector<int>& arr, int low, int high) {',
        '    int pivot = arr[high], i = low - 1;',
        '    for (int j = low; j < high; j++) {',
        '        if (arr[j] < pivot) swap(arr[++i], arr[j]);',
        '    }',
        '    swap(arr[i + 1], arr[high]);',
        '    return i + 1;',
        '}',
        '',
        'void quickSort(vector<int>& arr, int low, int high) {',
        '    if (low < high) {',
        '        int pi = partition(arr, low, high);',
        '        quickSort(arr, low, pi - 1);',
        '        quickSort(arr, pi + 1, high);',
        '    }',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    quickSort(arr, 0, arr.size() - 1);',
        '    cout << "Quick Sorted Array: ";',
        '    for (int x : arr) cout << x << " ";',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void quickSort(int[] arr, int low, int high) {', '    if (low < high) {', '        int pi = partition(arr, low, high);', '        quickSort(arr, low, pi - 1); quickSort(arr, pi + 1, high);', '    }', '}'],
      c: ['void quickSort(int arr[], int low, int high) {', '    if (low < high) {', '        int pi = partition(arr, low, high);', '        quickSort(arr, low, pi - 1); quickSort(arr, pi + 1, high);', '    }', '}']
    }
  },

  // --- SEARCHING ---
  linearSearch: {
    id: 'linearSearch',
    name: 'Linear Search',
    category: 'searching',
    description: 'Sequentially checks each element of list until match is found.',
    timeComplexity: { best: 'O(1)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function linearSearch(arr, target) {', '  for (let i = 0; i < arr.length; i++) if (arr[i] === target) return i;', '  return -1;', '}'],
      python: ['def linear_search(arr, target):', '    for i in range(len(arr)):', '        if arr[i] == target: return i', '    return -1'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int linearSearch(const vector<int>& arr, int target) {',
        '    for (size_t i = 0; i < arr.size(); i++) if (arr[i] == target) return (int)i;',
        '    return -1;',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {64, 34, 25, 12, 22, 11, 90};',
        '    int idx = linearSearch(arr, 22);',
        '    cout << "Found 22 at index: " << idx << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int linearSearch(int[] arr, int target) {', '    for (int i = 0; i < arr.length; i++) if (arr[i] == target) return i;', '    return -1;', '}'],
      c: ['int linearSearch(int arr[], int n, int target) {', '    for (int i = 0; i < n; i++) if (arr[i] == target) return i;', '    return -1;', '}']
    }
  },

  binarySearch: {
    id: 'binarySearch',
    name: 'Binary Search',
    category: 'searching',
    description: 'Searches a sorted array by repeatedly dividing search interval in half.',
    timeComplexity: { best: 'O(1)', average: 'O(log N)', worst: 'O(log N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function binarySearch(arr, target) {', '  let low = 0, high = arr.length - 1;', '  while (low <= high) {', '    let mid = Math.floor((low + high) / 2);', '    if (arr[mid] === target) return mid;', '    if (arr[mid] < target) low = mid + 1; else high = mid - 1;', '  }', '  return -1;', '}'],
      python: ['def binary_search(arr, target):', '    low, high = 0, len(arr) - 1', '    while low <= high:', '        mid = (low + high) // 2', '        if arr[mid] == target: return mid', '        elif arr[mid] < target: low = mid + 1', '        else: high = mid - 1', '    return -1'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int binarySearch(const vector<int>& arr, int target) {',
        '    int low = 0, high = arr.size() - 1;',
        '    while (low <= high) {',
        '        int mid = low + (high - low) / 2;',
        '        if (arr[mid] == target) return mid;',
        '        if (arr[mid] < target) low = mid + 1; else high = mid - 1;',
        '    }',
        '    return -1;',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {11, 12, 22, 25, 34, 64, 90};',
        '    int idx = binarySearch(arr, 34);',
        '    cout << "Binary Search found 34 at index: " << idx << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int binarySearch(int[] arr, int target) {', '    int low = 0, high = arr.length - 1;', '    while (low <= high) {', '        int mid = (low + high) / 2;', '        if (arr[mid] == target) return mid;', '        if (arr[mid] < target) low = mid + 1; else high = mid - 1;', '    }', '    return -1;', '}'],
      c: ['int binarySearch(int arr[], int n, int target) {', '    int low = 0, high = n - 1;', '    while (low <= high) {', '        int mid = low + (high - low) / 2;', '        if (arr[mid] == target) return mid;', '        if (arr[mid] < target) low = mid + 1; else high = mid - 1;', '    }', '    return -1;', '}']
    }
  },

  // --- BACKTRACKING ---
  nQueens: {
    id: 'nQueens',
    name: 'N-Queens Solver',
    category: 'backtracking',
    description: 'Places N non-attacking queens on an N×N chessboard.',
    timeComplexity: { best: 'O(N!)', average: 'O(N!)', worst: 'O(N!)' },
    spaceComplexity: 'O(N²)',
    stable: true,
    code: {
      javascript: ['function solveNQueens(board, col) {', '  if (col >= N) return true;', '  for (let i = 0; i < N; i++) {', '    if (isSafe(board, i, col)) {', '      board[i][col] = 1;', '      if (solveNQueens(board, col + 1)) return true;', '      board[i][col] = 0; // Backtrack', '    }', '  }', '  return false;', '}'],
      python: ['def solve_nqueens(board, col):', '    if col >= N: return True', '    for i in range(N):', '        if is_safe(board, i, col):', '            board[i][col] = 1', '            if solve_nqueens(board, col + 1): return True', '            board[i][col] = 0'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '#define N 4',
        '',
        'bool isSafe(int board[N][N], int row, int col) {',
        '    for (int i = 0; i < col; i++) if (board[row][i]) return false;',
        '    for (int i = row, j = col; i >= 0 && j >= 0; i--, j--) if (board[i][j]) return false;',
        '    for (int i = row, j = col; j >= 0 && i < N; i++, j--) if (board[i][j]) return false;',
        '    return true;',
        '}',
        '',
        'bool solveNQueens(int board[N][N], int col) {',
        '    if (col >= N) return true;',
        '    for (int i = 0; i < N; i++) {',
        '        if (isSafe(board, i, col)) {',
        '            board[i][col] = 1;',
        '            if (solveNQueens(board, col + 1)) return true;',
        '            board[i][col] = 0;',
        '        }',
        '    }',
        '    return false;',
        '}',
        '',
        'int main() {',
        '    int board[N][N] = {0};',
        '    if (solveNQueens(board, 0)) cout << "N-Queens Solution Found!" << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static boolean solveNQueens(int[][] board, int col) {', '    if (col >= N) return true;', '    for (int i = 0; i < N; i++) {', '        if (isSafe(board, i, col)) {', '            board[i][col] = 1;', '            if (solveNQueens(board, col + 1)) return true;', '            board[i][col] = 0;', '        }', '    }', '    return false;', '}'],
      c: ['bool solveNQueens(int board[N][N], int col) {', '    if (col >= N) return true;', '    for (int i = 0; i < N; i++) {', '        if (isSafe(board, i, col)) {', '            board[i][col] = 1;', '            if (solveNQueens(board, col + 1)) return true;', '            board[i][col] = 0;', '        }', '    }', '    return false;', '}']
    }
  },

  sudokuSolver: {
    id: 'sudokuSolver',
    name: 'Sudoku Solver',
    category: 'backtracking',
    description: 'Solves 9x9 Sudoku puzzle using backtracking search.',
    timeComplexity: { best: 'O(9^(N*N))', average: 'O(9^(N*N))', worst: 'O(9^(N*N))' },
    spaceComplexity: 'O(N²)',
    stable: true,
    code: {
      javascript: ['function solveSudoku(grid) {', '  for (let r = 0; r < 9; r++) {', '    for (let c = 0; c < 9; c++) {', '      if (grid[r][c] === 0) {', '        for (let num = 1; num <= 9; num++) {', '          if (isValid(grid, r, c, num)) { grid[r][c] = num; if (solveSudoku(grid)) return true; grid[r][c] = 0; }', '        }', '        return false;', '      }', '    }', '  }', '  return true;', '}'],
      python: ['def solve_sudoku(grid):', '    for r in range(9):', '        for c in range(9):', '            if grid[r][c] == 0:', '                for num in range(1, 10):', '                    if is_valid(grid, r, c, num):', '                        grid[r][c] = num', '                        if solve_sudoku(grid): return True', '                        grid[r][c] = 0', '                return False', '    return True'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'bool isValid(int grid[9][9], int r, int c, int num) {',
        '    for (int i = 0; i < 9; i++) if (grid[r][i] == num || grid[i][c] == num) return false;',
        '    int startRow = r - r % 3, startCol = c - c % 3;',
        '    for (int i = 0; i < 3; i++) for (int j = 0; j < 3; j++) if (grid[i + startRow][j + startCol] == num) return false;',
        '    return true;',
        '}',
        '',
        'bool solveSudoku(int grid[9][9]) {',
        '    for (int r = 0; r < 9; r++) {',
        '        for (int c = 0; c < 9; c++) {', '            if (grid[r][c] == 0) {',
        '                for (int num = 1; num <= 9; num++) {',
        '                    if (isValid(grid, r, c, num)) { grid[r][c] = num; if (solveSudoku(grid)) return true; grid[r][c] = 0; }',
        '                }',
        '                return false;',
        '            }',
        '        }',
        '    }',
        '    return true;',
        '}',
        '',
        'int main() {',
        '    int grid[9][9] = {0};',
        '    if (solveSudoku(grid)) cout << "Sudoku Grid Solved!" << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static boolean solveSudoku(int[][] grid) {', '    for (int r = 0; r < 9; r++) {', '        for (int c = 0; c < 9; c++) {', '            if (grid[r][c] == 0) {', '                for (int num = 1; num <= 9; num++) {', '                    if (isValid(grid, r, c, num)) { grid[r][c] = num; if (solveSudoku(grid)) return true; grid[r][c] = 0; }', '                }', '                return false;', '            }', '        }', '    }', '    return true;', '}'],
      c: ['bool solveSudoku(int grid[9][9]) {', '    for (int r = 0; r < 9; r++) {', '        for (int c = 0; c < 9; c++) {', '            if (grid[r][c] == 0) {', '                for (int num = 1; num <= 9; num++) {', '                    if (isValid(grid, r, c, num)) { grid[r][c] = num; if (solveSudoku(grid)) return true; grid[r][c] = 0; }', '                }', '                return false;', '            }', '        }', '    }', '    return true;', '}']
    }
  },

  ratInMaze: {
    id: 'ratInMaze',
    name: 'Rat in a Maze',
    category: 'backtracking',
    description: 'Finds path for rat to reach destination in N×N grid with obstacles.',
    timeComplexity: { best: 'O(2^(N²))', average: 'O(2^(N²))', worst: 'O(2^(N²))' },
    spaceComplexity: 'O(N²)',
    stable: true,
    code: {
      javascript: ['function solveMaze(maze, x, y, sol) {', '  if (x === N - 1 && y === N - 1) { sol[x][y] = 1; return true; }', '  if (isSafe(maze, x, y)) {', '    sol[x][y] = 1;', '    if (solveMaze(maze, x + 1, y, sol)) return true;', '    if (solveMaze(maze, x, y + 1, sol)) return true;', '    sol[x][y] = 0; // Backtrack', '  }', '  return false;', '}'],
      python: ['def solve_maze(maze, x, y, sol):', '    if x == N - 1 and y == N - 1: sol[x][y] = 1; return True', '    if is_safe(maze, x, y):', '        sol[x][y] = 1', '        if solve_maze(maze, x + 1, y, sol): return True', '        if solve_maze(maze, x, y + 1, sol): return True', '        sol[x][y] = 0', '    return False'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '#define N 4',
        '',
        'bool isSafe(int maze[N][N], int x, int y) {',
        '    return (x >= 0 && x < N && y >= 0 && y < N && maze[x][y] == 1);',
        '}',
        '',
        'bool solveMaze(int maze[N][N], int x, int y, int sol[N][N]) {',
        '    if (x == N - 1 && y == N - 1) { sol[x][y] = 1; return true; }',
        '    if (isSafe(maze, x, y)) {',
        '        sol[x][y] = 1;',
        '        if (solveMaze(maze, x + 1, y, sol)) return true;',
        '        if (solveMaze(maze, x, y + 1, sol)) return true;',
        '        sol[x][y] = 0;',
        '    }',
        '    return false;',
        '}',
        '',
        'int main() {',
        '    int maze[N][N] = {{1,0,0,0},{1,1,0,1},{0,1,0,0},{1,1,1,1}};',
        '    int sol[N][N] = {0};',
        '    if (solveMaze(maze, 0, 0, sol)) cout << "Maze Path Found!" << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static boolean solveMaze(int[][] maze, int x, int y, int[][] sol) {', '    if (x == N - 1 && y == N - 1) { sol[x][y] = 1; return true; }', '    if (isSafe(maze, x, y)) {', '        sol[x][y] = 1;', '        if (solveMaze(maze, x + 1, y, sol)) return true;', '        if (solveMaze(maze, x, y + 1, sol)) return true;', '        sol[x][y] = 0;', '    }', '    return false;', '}'],
      c: ['bool solveMaze(int maze[N][N], int x, int y, int sol[N][N]) {', '    if (x == N - 1 && y == N - 1) { sol[x][y] = 1; return true; }', '    if (isSafe(maze, x, y)) {', '        sol[x][y] = 1;', '        if (solveMaze(maze, x + 1, y, sol)) return true;', '        if (solveMaze(maze, x, y + 1, sol)) return true;', '        sol[x][y] = 0;', '    }', '    return false;', '}']
    }
  },

  symmetricTree: {
    id: 'symmetricTree',
    name: 'Symmetric Tree Verification',
    category: 'trees',
    description: 'Checks whether a binary tree is a mirror of itself (symmetric around center).',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function isSymmetric(root) {', '  if (!root) return true;', '  function isMirror(t1, t2) {', '    if (!t1 && !t2) return true;', '    if (!t1 || !t2) return false;', '    return (t1.val === t2.val) && isMirror(t1.right, t2.left) && isMirror(t1.left, t2.right);', '  }', '  return isMirror(root.left, root.right);', '}'],
      python: ['def is_symmetric(root):', '    if not root: return True', '    def is_mirror(t1, t2):', '        if not t1 and not t2: return True', '        if not t1 or not t2: return False', '        return (t1.val == t2.val) and is_mirror(t1.right, t2.left) and is_mirror(t1.left, t2.right)', '    return is_mirror(root.left, root.right)'],
      cpp: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'struct TreeNode {',
        '    int val;',
        '    TreeNode *left, *right;',
        '    TreeNode(int x) : val(x), left(NULL), right(NULL) {}',
        '};',
        '',
        'bool isMirror(TreeNode* t1, TreeNode* t2) {',
        '    if (!t1 && !t2) return true;',
        '    if (!t1 || !t2) return false;',
        '    return (t1->val == t2->val) && isMirror(t1->right, t2->left) && isMirror(t1->left, t2->right);',
        '}',
        '',
        'bool isSymmetric(TreeNode* root) {',
        '    return root == NULL || isMirror(root->left, root->right);',
        '}',
        '',
        'int main() {',
        '    TreeNode* root = new TreeNode(1);',
        '    root->left = new TreeNode(2);',
        '    root->right = new TreeNode(2);',
        '    cout << "Is Symmetric Tree: " << (isSymmetric(root) ? "Yes" : "No") << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static boolean isSymmetric(TreeNode root) {', '    return root == null || isMirror(root.left, root.right);', '}', 'private static boolean isMirror(TreeNode t1, TreeNode t2) {', '    if (t1 == null && t2 == null) return true;', '    if (t1 == null || t2 == null) return false;', '    return (t1.val == t2.val) && isMirror(t1.right, t2.left) && isMirror(t1.left, t2.right);', '}'],
      c: ['bool isMirror(struct TreeNode* t1, struct TreeNode* t2) {', '    if (!t1 && !t2) return true;', '    if (!t1 || !t2) return false;', '    return (t1->val == t2->val) && isMirror(t1->right, t2->left) && isMirror(t1.left, t2.right);', '}', 'bool isSymmetric(struct TreeNode* root) {', '    return root == NULL || isMirror(root->left, root->right);', '}']
    }
  },

  // --- GRAPHS ---
  bfs: {
    id: 'bfs',
    name: 'Breadth-First Search (BFS)',
    category: 'graphs',
    description: 'Traverses graph level-by-level using Queue data structure.',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    code: {
      javascript: ['function bfs(graph, startNode) {', '  let visited = new Set([startNode]);', '  let queue = [startNode];', '  while (queue.length > 0) {', '    let node = queue.shift();', '    for (let neighbor of graph[node]) if (!visited.has(neighbor)) { visited.add(neighbor); queue.push(neighbor); }', '  }', '}'],
      python: ['from collections import deque', 'def bfs(graph, start):', '    visited = {start}; queue = deque([start])', '    while queue:', '        node = queue.popleft()', '        for neighbor in graph[node]:', '            if neighbor not in visited: visited.add(neighbor); queue.append(neighbor)'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <queue>',
        '#include <unordered_set>',
        'using namespace std;',
        '',
        'void bfs(int start, vector<vector<int>>& adj, int V) {',
        '    vector<bool> visited(V, false);',
        '    queue<int> q;',
        '    visited[start] = true; q.push(start);',
        '    cout << "BFS Traversal: ";',
        '    while (!q.empty()) {',
        '        int curr = q.front(); q.pop();',
        '        cout << curr << " ";',
        '        for (int neighbor : adj[curr]) if (!visited[neighbor]) { visited[neighbor] = true; q.push(neighbor); }',
        '    }',
        '    cout << endl;',
        '}',
        '',
        'int main() {',
        '    vector<vector<int>> adj = {{1, 2}, {0, 3}, {0, 3}, {1, 2}};',
        '    bfs(0, adj, 4);',
        '    return 0;',
        '}'
      ],
      java: ['public static void bfs(Map<Character, List<Character>> graph, char start) {', '    Set<Character> visited = new HashSet<>(); Queue<Character> queue = new LinkedList<>();', '    visited.add(start); queue.add(start);', '    while (!queue.isEmpty()) {', '        char node = queue.poll();', '        for (char neighbor : graph.get(node)) if (!visited.contains(neighbor)) { visited.add(neighbor); queue.add(neighbor); }', '    }', '}'],
      c: ['void bfs(int adj[][MAX], int numNodes, int start) {', '    int visited[MAX] = {0}, queue[MAX], front = 0, rear = 0;', '    visited[start] = 1; queue[rear++] = start;', '    while (front < rear) {', '        int node = queue[front++];', '        for (int i = 0; i < numNodes; i++) if (adj[node][i] && !visited[i]) { visited[i] = 1; queue[rear++] = i; }', '    }', '}']
    }
  },

  dfs: {
    id: 'dfs',
    name: 'Depth-First Search (DFS)',
    category: 'graphs',
    description: 'Traverses graph by exploring as far as possible along each branch before backtracking.',
    timeComplexity: { best: 'O(V + E)', average: 'O(V + E)', worst: 'O(V + E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    code: {
      javascript: ['function dfs(graph, node, visited = new Set()) {', '  visited.add(node);', '  for (let neighbor of graph[node]) if (!visited.has(neighbor)) dfs(graph, neighbor, visited);', '}'],
      python: ['def dfs(graph, node, visited=None):', '    if visited is None: visited = set()', '    visited.add(node)', '    for neighbor in graph[node]:', '        if neighbor not in visited: dfs(graph, neighbor, visited)'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'void dfs(int curr, vector<vector<int>>& adj, vector<bool>& visited) {',
        '    visited[curr] = true;',
        '    cout << curr << " ";',
        '    for (int neighbor : adj[curr]) if (!visited[neighbor]) dfs(neighbor, adj, visited);',
        '}',
        '',
        'int main() {',
        '    vector<vector<int>> adj = {{1, 2}, {0, 3}, {0, 3}, {1, 2}};',
        '    vector<bool> visited(4, false);',
        '    cout << "DFS Traversal: ";',
        '    dfs(0, adj, visited);',
        '    cout << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static void dfs(Map<Character, List<Character>> graph, char node, Set<Character> visited) {', '    visited.add(node);', '    for (char neighbor : graph.get(node)) if (!visited.contains(neighbor)) dfs(graph, neighbor, visited);', '}'],
      c: ['void dfs(int adj[][MAX], int visited[], int numNodes, int node) {', '    visited[node] = 1;', '    for (int i = 0; i < numNodes; i++) if (adj[node][i] && !visited[i]) dfs(adj, visited, numNodes, i);', '}']
    }
  },

  dijkstra: {
    id: 'dijkstra',
    name: "Dijkstra's Shortest Path",
    category: 'graphs',
    description: 'Finds shortest paths between nodes in weighted graph.',
    timeComplexity: { best: 'O((V + E) log V)', average: 'O((V + E) log V)', worst: 'O(V²)' },
    spaceComplexity: 'O(V)',
    stable: true,
    code: {
      javascript: ['function dijkstra(graph, source) {', '  let dist = {}; let pq = new MinPriorityQueue();', '  dist[source] = 0; pq.insert(source, 0);', '  while (!pq.isEmpty()) {', '    let { node } = pq.extractMin();', '    for (let neighbor of graph[node]) {', '      if (dist[node] + neighbor.weight < dist[neighbor.to]) {', '        dist[neighbor.to] = dist[node] + neighbor.weight; pq.insert(neighbor.to, dist[neighbor.to]);', '      }', '    }', '  }', '}'],
      python: ['import heapq', 'def dijkstra(graph, start):', '    dist = {node: float("inf") for node in graph}; dist[start] = 0; pq = [(0, start)]', '    while pq:', '        d, curr = heapq.heappop(pq)', '        for neighbor, weight in graph[curr]:', '            if dist[curr] + weight < dist[neighbor]:', '                dist[neighbor] = dist[curr] + weight; heapq.heappush(pq, (dist[neighbor], neighbor))'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <queue>',
        '#include <climits>',
        'using namespace std;',
        '',
        'void dijkstra(int start, vector<pair<int, int>> adj[], int V) {',
        '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<>> pq;',
        '    vector<int> dist(V, INT_MAX);',
        '    dist[start] = 0; pq.push({0, start});',
        '    while (!pq.empty()) {',
        '        int u = pq.top().second; pq.pop();',
        '        for (auto edge : adj[u]) {',
        '            int v = edge.first, weight = edge.second;',
        '            if (dist[u] + weight < dist[v]) { dist[v] = dist[u] + weight; pq.push({dist[v], v}); }',
        '        }',
        '    }',
        '    cout << "Dijkstra Shortest Distance from " << start << ": " << dist[V-1] << endl;',
        '}',
        '',
        'int main() {',
        '    vector<pair<int, int>> adj[4];',
        '    adj[0].push_back({1, 4}); adj[0].push_back({2, 2});',
        '    adj[1].push_back({3, 5}); adj[2].push_back({3, 8});',
        '    dijkstra(0, adj, 4);',
        '    return 0;',
        '}'
      ],
      java: ['public static void dijkstra(int start, List<int[]>[] adj, int V) {', '    PriorityQueue<int[]> pq = new PriorityQueue<>(Comparator.comparingInt(a -> a[1])); int[] dist = new int[V]; Arrays.fill(dist, Integer.MAX_VALUE);', '    dist[start] = 0; pq.add(new int[]{start, 0});', '    while (!pq.isEmpty()) {', '        int u = pq.poll()[0];', '        for (int[] edge : adj[u]) {', '            int v = edge[0], weight = edge[1];', '            if (dist[u] + weight < dist[v]) { dist[v] = dist[u] + weight; pq.add(new int[]{v, dist[v]}); }', '        }', '    }', '}'],
      c: ['void dijkstra(int graph[V][V], int src) {', '    int dist[V], visited[V] = {0}; for (int i = 0; i < V; i++) dist[i] = INT_MAX; dist[src] = 0;', '    for (int count = 0; count < V - 1; count++) {', '        int u = minDistance(dist, visited); visited[u] = 1;', '        for (int v = 0; v < V; v++) if (!visited[v] && graph[u][v] && dist[u] + graph[u][v] < dist[v]) dist[v] = dist[u] + graph[u][v];', '    }', '}']
    }
  },

  // --- TREES ---
  bst: {
    id: 'bst',
    name: 'Binary Search Tree (BST)',
    category: 'trees',
    description: 'Tree data structure where left child < parent and right child > parent.',
    timeComplexity: { best: 'O(log N)', average: 'O(log N)', worst: 'O(N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function insertBST(root, val) {', '  if (!root) return new TreeNode(val);', '  if (val < root.val) root.left = insertBST(root.left, val);', '  else root.right = insertBST(root.right, val);', '  return root;', '}'],
      python: ['def insert_bst(root, val):', '    if not root: return TreeNode(val)', '    if val < root.val: root.left = insert_bst(root.left, val)', '    else: root.right = insert_bst(root.right, val)', '    return root'],
      cpp: [
        '#include <iostream>',
        'using namespace std;',
        '',
        'struct TreeNode {',
        '    int val;',
        '    TreeNode *left, *right;',
        '    TreeNode(int x) : val(x), left(NULL), right(NULL) {}',
        '};',
        '',
        'TreeNode* insertBST(TreeNode* root, int val) {',
        '    if (!root) return new TreeNode(val);',
        '    if (val < root->val) root->left = insertBST(root->left, val);',
        '    else root->right = insertBST(root->right, val);',
        '    return root;',
        '}',
        '',
        'int main() {',
        '    TreeNode* root = NULL;',
        '    int arr[] = {45, 12, 89, 34, 67, 23};',
        '    for (int x : arr) root = insertBST(root, x);',
        '    cout << "Root node of BST: " << root->val << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static TreeNode insertBST(TreeNode root, int val) {', '    if (root == null) return new TreeNode(val);', '    if (val < root.val) root.left = insertBST(root.left, val);', '    else root.right = insertBST(root.right, val);', '    return root;', '}'],
      c: ['struct Node* insertBST(struct Node* node, int val) {', '    if (node == NULL) return newNode(val);', '    if (val < node->key) node->left = insertBST(node->left, val);', '    else if (val > node->key) node->right = insertBST(node->right, val);', '    return node;', '}']
    }
  },

  // --- DYNAMIC PROGRAMMING ---
  knapsack: {
    id: 'knapsack',
    name: '0/1 Knapsack',
    category: 'dp',
    description: 'Determines subset of items to include in knapsack to maximize total value.',
    timeComplexity: { best: 'O(N * W)', average: 'O(N * W)', worst: 'O(N * W)' },
    spaceComplexity: 'O(N * W)',
    stable: true,
    code: {
      javascript: ['function knapsack(W, wt, val, n) {', '  let dp = Array(n + 1).fill(0).map(() => Array(W + 1).fill(0));', '  for (let i = 1; i <= n; i++) {', '    for (let w = 1; w <= W; w++) {', '      if (wt[i-1] <= w) dp[i][w] = Math.max(val[i-1] + dp[i-1][w - wt[i-1]], dp[i-1][w]);', '      else dp[i][w] = dp[i-1][w];', '    }', '  }', '  return dp[n][W];', '}'],
      python: ['def knapsack(W, wt, val, n):', '    dp = [[0] * (W + 1) for _ in range(n + 1)]', '    for i in range(1, n + 1):', '        for w in range(1, W + 1):', '            if wt[i-1] <= w: dp[i][w] = max(val[i-1] + dp[i-1][w - wt[i-1]], dp[i-1][w])', '            else: dp[i][w] = dp[i-1][w]', '    return dp[n][W]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int knapsack(int W, const vector<int>& wt, const vector<int>& val, int n) {',
        '    vector<vector<int>> dp(n + 1, vector<int>(W + 1, 0));',
        '    for (int i = 1; i <= n; i++) {',
        '        for (int w = 1; w <= W; w++) {',
        '            if (wt[i-1] <= w) dp[i][w] = max(val[i-1] + dp[i-1][w - wt[i-1]], dp[i-1][w]);',
        '            else dp[i][w] = dp[i-1][w];',
        '        }',
        '    }',
        '    return dp[n][W];',
        '}',
        '',
        'int main() {',
        '    vector<int> wt = {2, 3, 4, 5};',
        '    vector<int> val = {3, 4, 5, 6};',
        '    cout << "Max Knapsack Value: " << knapsack(5, wt, val, 4) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int knapsack(int W, int[] wt, int[] val, int n) {', '    int[][] dp = new int[n + 1][W + 1];', '    for (int i = 1; i <= n; i++) {', '        for (int w = 1; w <= W; w++) {', '            if (wt[i-1] <= w) dp[i][w] = Math.max(val[i-1] + dp[i-1][w - wt[i-1]], dp[i-1][w]);', '            else dp[i][w] = dp[i-1][w];', '        }', '    }', '    return dp[n][W];', '}'],
      c: ['int knapsack(int W, int wt[], int val[], int n) {', '    int dp[n + 1][W + 1];', '    for (int i = 0; i <= n; i++) {', '        for (int w = 0; w <= W; w++) {', '            if (i == 0 || w == 0) dp[i][w] = 0;', '            else if (wt[i-1] <= w) dp[i][w] = max(val[i-1] + dp[i-1][w - wt[i-1]], dp[i-1][w]);', '            else dp[i][w] = dp[i-1][w];', '        }', '    }', '    return dp[n][W];', '}']
    }
  },

  lcs: {
    id: 'lcs',
    name: 'Longest Common Subsequence',
    category: 'dp',
    description: 'Finds longest subsequence common to two string sequences.',
    timeComplexity: { best: 'O(M * N)', average: 'O(M * N)', worst: 'O(M * N)' },
    spaceComplexity: 'O(M * N)',
    stable: true,
    code: {
      javascript: ['function lcs(text1, text2) {', '  let m = text1.length, n = text2.length;', '  let dp = Array(m + 1).fill(0).map(() => Array(n + 1).fill(0));', '  for (let i = 1; i <= m; i++) {', '    for (let j = 1; j <= n; j++) {', '      if (text1[i-1] === text2[j-1]) dp[i][j] = dp[i-1][j-1] + 1;', '      else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);', '    }', '  }', '  return dp[m][n];', '}'],
      python: ['def lcs(text1, text2):', '    m, n = len(text1), len(text2)', '    dp = [[0] * (n + 1) for _ in range(m + 1)]', '    for i in range(1, m + 1):', '        for j in range(1, n + 1):', '            if text1[i-1] == text2[j-1]: dp[i][j] = dp[i-1][j-1] + 1', '            else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])', '    return dp[m][n]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <string>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int lcs(string text1, string text2) {',
        '    int m = text1.size(), n = text2.size();',
        '    vector<vector<int>> dp(m + 1, vector<int>(n + 1, 0));',
        '    for (int i = 1; i <= m; i++) {',
        '        for (int j = 1; j <= n; j++) {',
        '            if (text1[i-1] == text2[j-1]) dp[i][j] = dp[i-1][j-1] + 1;',
        '            else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);',
        '        }',
        '    }',
        '    return dp[m][n];',
        '}',
        '',
        'int main() {',
        '    cout << "LCS Length: " << lcs("STONE", "LONGEST") << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int lcs(String text1, String text2) {', '    int m = text1.length(), n = text2.length();', '    int[][] dp = new int[m + 1][n + 1];', '    for (int i = 1; i <= m; i++) {', '        for (int j = 1; j <= n; j++) {', '            if (text1.charAt(i-1) == text2.charAt(j-1)) dp[i][j] = dp[i-1][j-1] + 1;', '            else dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);', '        }', '    }', '    return dp[m][n];', '}'],
      c: ['int lcs(char* text1, char* text2, int m, int n) {', '    int dp[m + 1][n + 1];', '    for (int i = 0; i <= m; i++) {', '        for (int j = 0; j <= n; j++) {', '            if (i == 0 || j == 0) dp[i][j] = 0;', '            else if (text1[i-1] == text2[j-1]) dp[i][j] = dp[i-1][j-1] + 1;', '            else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);', '        }', '    }', '    return dp[m][n];', '}']
    }
  },

  climbingStairs: {
    id: 'climbingStairs',
    name: 'Climbing Stairs',
    category: 'dp',
    description: 'Finds total distinct ways to reach top of N stairs taking 1 or 2 steps at a time.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function climbStairs(n) {', '  let dp = Array(n + 1).fill(0);', '  dp[0] = 1; dp[1] = 1;', '  for (let i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '  return dp[n];', '}'],
      python: ['def climb_stairs(n):', '    dp = [0] * (n + 1); dp[0] = 1; dp[1] = 1', '    for i in range(2, n + 1): dp[i] = dp[i - 1] + dp[i - 2]', '    return dp[n]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int climbStairs(int n) {',
        '    vector<int> dp(n + 1, 0); dp[0] = 1; dp[1] = 1;',
        '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];',
        '    return dp[n];',
        '}',
        '',
        'int main() {',
        '    cout << "Ways to climb 5 stairs: " << climbStairs(5) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int climbStairs(int n) {', '    int[] dp = new int[n + 1]; dp[0] = 1; dp[1] = 1;', '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '    return dp[n];', '}'],
      c: ['int climbStairs(int n) {', '    int dp[n + 1]; dp[0] = 1; dp[1] = 1;', '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '    return dp[n];', '}']
    }
  },

  fibonacciDP: {
    id: 'fibonacciDP',
    name: 'Fibonacci Series',
    category: 'dp',
    description: 'Calculates N-th Fibonacci number in O(N) time using Memoization / Tabulation.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function fibonacciDP(n) {', '  let dp = Array(n + 1).fill(0);', '  dp[0] = 0; dp[1] = 1;', '  for (let i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '  return dp[n];', '}'],
      python: ['def fibonacci_dp(n):', '    dp = [0] * (n + 1); dp[0] = 0; dp[1] = 1', '    for i in range(2, n + 1): dp[i] = dp[i - 1] + dp[i - 2]', '    return dp[n]'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int fibonacciDP(int n) {',
        '    if (n <= 1) return n;',
        '    vector<int> dp(n + 1, 0); dp[0] = 0; dp[1] = 1;',
        '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];',
        '    return dp[n];',
        '}',
        '',
        'int main() {',
        '    cout << "10th Fibonacci Term: " << fibonacciDP(10) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int fibonacciDP(int n) {', '    int[] dp = new int[n + 1]; dp[0] = 0; dp[1] = 1;', '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '    return dp[n];', '}'],
      c: ['int fibonacciDP(int n) {', '    int dp[n + 1]; dp[0] = 0; dp[1] = 1;', '    for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];', '    return dp[n];', '}']
    }
  },

  kadanesAlgo: {
    id: 'kadanesAlgo',
    name: "Kadane's Algorithm",
    category: 'dp',
    description: 'Finds maximum sum contiguous subarray in O(N) time and O(1) space.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function maxSubArray(nums) {', '  let maxSoFar = nums[0], currMax = nums[0];', '  for (let i = 1; i < nums.length; i++) {', '    currMax = Math.max(nums[i], currMax + nums[i]);', '    maxSoFar = Math.max(maxSoFar, currMax);', '  }', '  return maxSoFar;', '}'],
      python: ['def max_sub_array(nums):', '    max_so_far = curr_max = nums[0]', '    for x in nums[1:]:', '        curr_max = max(x, curr_max + x)', '        max_so_far = max(max_so_far, curr_max)', '    return max_so_far'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int maxSubArray(const vector<int>& nums) {',
        '    int maxSoFar = nums[0], currMax = nums[0];',
        '    for (size_t i = 1; i < nums.size(); i++) {',
        '        currMax = max(nums[i], currMax + nums[i]);',
        '        maxSoFar = max(maxSoFar, currMax);',
        '    }',
        '    return maxSoFar;',
        '}',
        '',
        'int main() {',
        '    vector<int> nums = {-2, 1, -3, 4, -1, 2, 1, -5, 4};',
        '    cout << "Maximum Subarray Sum: " << maxSubArray(nums) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int maxSubArray(int[] nums) {', '    int maxSoFar = nums[0], currMax = nums[0];', '    for (int i = 1; i < nums.length; i++) {', '        currMax = Math.max(nums[i], currMax + nums[i]);', '        maxSoFar = Math.max(maxSoFar, currMax);', '    }', '    return maxSoFar;', '}'],
      c: ['int maxSubArray(int nums[], int n) {', '    int maxSoFar = nums[0], currMax = nums[0];', '    for (int i = 1; i < n; i++) {', '        currMax = nums[i] > (currMax + nums[i]) ? nums[i] : (currMax + nums[i]);', '        if (currMax > maxSoFar) maxSoFar = currMax;', '    }', '    return maxSoFar;', '}']
    }
  },

  // --- GREEDY ALGORITHMS ---
  activitySelection: {
    id: 'activitySelection',
    name: 'Activity Selection Problem',
    category: 'greedy',
    description: 'Selects maximum number of non-overlapping activities sorted by finish time.',
    timeComplexity: { best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N log N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function selectActivities(s, f) {', '  let selected = [0]; let lastFinish = f[0];', '  for (let i = 1; i < s.length; i++) {', '    if (s[i] >= lastFinish) { selected.push(i); lastFinish = f[i]; }', '  }', '  return selected;', '}'],
      python: ['def activity_selection(s, f):', '    selected = [0]; last_finish = f[0]', '    for i in range(1, len(s)):', '        if s[i] >= last_finish: selected.append(i); last_finish = f[i]', '    return selected'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'void activitySelection(const vector<int>& s, const vector<int>& f) {',
        '    cout << "Selected Activities: 0 ";',
        '    int lastFinish = f[0];',
        '    for (size_t i = 1; i < s.size(); i++) {',
        '        if (s[i] >= lastFinish) { cout << i << " "; lastFinish = f[i]; }',
        '    }',
        '    cout << endl;',
        '}',
        '',
        'int main() {',
        '    vector<int> s = {1, 3, 0, 5, 8, 5};',
        '    vector<int> f = {2, 4, 6, 7, 9, 9};',
        '    activitySelection(s, f);',
        '    return 0;',
        '}'
      ],
      java: ['public static List<Integer> activitySelection(int[] s, int[] f) {', '    List<Integer> res = new ArrayList<>(); res.add(0); int lastFinish = f[0];', '    for (int i = 1; i < s.length; i++) {', '        if (s[i] >= lastFinish) { res.add(i); lastFinish = f[i]; }', '    }', '    return res;', '}'],
      c: ['void activitySelection(int s[], int f[], int n) {', '    int i = 0; printf("%d ", i);', '    for (int j = 1; j < n; j++) {', '        if (s[j] >= f[i]) { printf("%d ", j); i = j; }', '    }', '}']
    }
  },

  fractionalKnapsack: {
    id: 'fractionalKnapsack',
    name: 'Fractional Knapsack',
    category: 'greedy',
    description: 'Greedy knapsack taking fractions of items based on value-to-weight ratio.',
    timeComplexity: { best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N log N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function fractionalKnapsack(capacity, items) {', '  items.sort((a, b) => (b.val / b.wt) - (a.val / a.wt));', '  let totalVal = 0;', '  for (let item of items) {', '    if (capacity >= item.wt) { capacity -= item.wt; totalVal += item.val; }', '    else { totalVal += item.val * (capacity / item.wt); break; }', '  }', '  return totalVal;', '}'],
      python: ['def fractional_knapsack(capacity, items):', '    items.sort(key=lambda x: x.val / x.wt, reverse=True); total_val = 0', '    for item in items:', '        if capacity >= item.wt: capacity -= item.wt; total_val += item.val', '        else: total_val += item.val * (capacity / item.wt); break', '    return total_val'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'struct Item { int val, wt; };',
        '',
        'double fractionalKnapsack(int W, vector<Item>& items) {',
        '    sort(items.begin(), items.end(), [](Item a, Item b){ return (double)a.val/a.wt > (double)b.val/b.wt; });',
        '    double totalVal = 0.0;',
        '    for (auto item : items) {',
        '        if (W >= item.wt) { W -= item.wt; totalVal += item.val; }',
        '        else { totalVal += item.val * ((double)W / item.wt); break; }',
        '    }',
        '    return totalVal;',
        '}',
        '',
        'int main() {',
        '    vector<Item> items = {{60, 10}, {100, 20}, {120, 30}};',
        '    cout << "Max Fractional Value: " << fractionalKnapsack(50, items) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static double fractionalKnapsack(int W, Item[] items) {', '    Arrays.sort(items, (a, b) -> Double.compare((double)b.val/b.wt, (double)a.val/a.wt));', '    double totalVal = 0.0;', '    for (Item item : items) {', '        if (W >= item.wt) { W -= item.wt; totalVal += item.val; }', '        else { totalVal += item.val * ((double)W / item.wt); break; }', '    }', '    return totalVal;', '}'],
      c: ['double fractionalKnapsack(int W, struct Item items[], int n) {', '    qsort(items, n, sizeof(items[0]), compareItems); double totalVal = 0.0;', '    for (int i = 0; i < n; i++) {', '        if (W >= items[i].wt) { W -= items[i].wt; totalVal += items[i].val; }', '        else { totalVal += items[i].val * ((double)W / items[i].wt); break; }', '    }', '    return totalVal;', '}']
    }
  },

  boatsToSavePeople: {
    id: 'boatsToSavePeople',
    name: 'Boats to Save People',
    category: 'greedy',
    description: 'Greedy pairing of heaviest and lightest people within boat weight limit.',
    timeComplexity: { best: 'O(N log N)', average: 'O(N log N)', worst: 'O(N log N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function numRescueBoats(people, limit) {', '  people.sort((a, b) => a - b);', '  let left = 0, right = people.length - 1, boats = 0;', '  while (left <= right) {', '    if (people[left] + people[right] <= limit) left++;', '    right--; boats++;', '  }', '  return boats;', '}'],
      python: ['def num_rescue_boats(people, limit):', '    people.sort()', '    left, right, boats = 0, len(people) - 1, 0', '    while left <= right:', '        if people[left] + people[right] <= limit: left += 1', '        right -= 1; boats += 1', '    return boats'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int numRescueBoats(vector<int>& people, int limit) {',
        '    sort(people.begin(), people.end());',
        '    int left = 0, right = people.size() - 1, boats = 0;',
        '    while (left <= right) {',
        '        if (people[left] + people[right] <= limit) left++;',
        '        right--; boats++;',
        '    }',
        '    return boats;',
        '}',
        '',
        'int main() {',
        '    vector<int> people = {3, 2, 2, 1};',
        '    cout << "Minimum Boats Needed: " << numRescueBoats(people, 3) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int numRescueBoats(int[] people, int limit) {', '    Arrays.sort(people);', '    int left = 0, right = people.length - 1, boats = 0;', '    while (left <= right) {', '        if (people[left] + people[right] <= limit) left++;', '        right--; boats++;', '    }', '    return boats;', '}'],
      c: ['int numRescueBoats(int people[], int n, int limit) {', '    qsort(people, n, sizeof(int), compare);', '    int left = 0, right = n - 1, boats = 0;', '    while (left <= right) {', '        if (people[left] + people[right] <= limit) left++;', '        right--; boats++;', '    }', '    return boats;', '}']
    }
  },

  stonePile: {
    id: 'stonePile',
    name: 'Stone Piles Removal',
    category: 'greedy',
    description: 'Greedy max heap reduction to minimize total remaining stones in K operations.',
    timeComplexity: { best: 'O(K log N)', average: 'O(K log N)', worst: 'O(K log N)' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function minStoneSum(piles, k) {', '  let maxHeap = new MaxPriorityQueue();', '  piles.forEach(p => maxHeap.enqueue(p));', '  for (let i = 0; i < k; i++) {', '    let maxVal = maxHeap.dequeue().element;', '    maxHeap.enqueue(maxVal - Math.floor(maxVal / 2));', '  }', '  return maxHeap.toArray().reduce((a, b) => a + b.element, 0);', '}'],
      python: ['import heapq', 'def min_stone_sum(piles, k):', '    piles = [-p for p in piles]; heapq.heapify(piles)', '    for _ in range(k):', '        max_val = -heapq.heappop(piles)', '        heapq.heappush(piles, -(max_val - max_val // 2))', '    return -sum(piles)'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <queue>',
        'using namespace std;',
        '',
        'int minStoneSum(vector<int>& piles, int k) {',
        '    priority_queue<int> pq(piles.begin(), piles.end());',
        '    for (int i = 0; i < k; i++) {',
        '        int maxVal = pq.top(); pq.pop();',
        '        pq.push(maxVal - maxVal / 2);',
        '    }',
        '    int sum = 0; while (!pq.empty()) { sum += pq.top(); pq.pop(); } return sum;',
        '}',
        '',
        'int main() {',
        '    vector<int> piles = {5, 4, 9};',
        '    cout << "Min Stones Remaining: " << minStoneSum(piles, 2) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int minStoneSum(int[] piles, int k) {', '    PriorityQueue<Integer> pq = new PriorityQueue<>(Collections.reverseOrder());', '    for (int p : piles) pq.add(p);', '    for (int i = 0; i < k; i++) { int maxVal = pq.poll(); pq.add(maxVal - maxVal / 2); }', '    int sum = 0; for (int p : pq) sum += p; return sum;', '}'],
      c: ['int minStoneSum(int piles[], int n, int k) {', '    for (int i = 0; i < k; i++) {', '        int maxIdx = 0;', '        for (int j = 1; j < n; j++) if (piles[j] > piles[maxIdx]) maxIdx = j;', '        piles[maxIdx] -= piles[maxIdx] / 2;', '    }', '    int sum = 0; for (int i = 0; i < n; i++) sum += piles[i]; return sum;', '}']
    }
  },

  // --- TWO POINTERS ---
  twoSumSorted: {
    id: 'twoSumSorted',
    name: 'Two Sum (Sorted Array)',
    category: 'twoPointers',
    description: 'Finds two numbers in sorted array that sum up to target in O(N) time.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function twoSumSorted(arr, target) {', '  let left = 0, right = arr.length - 1;', '  while (left < right) {', '    let sum = arr[left] + arr[right];', '    if (sum === target) return [left, right];', '    if (sum < target) left++; else right--;', '  }', '  return [];', '}'],
      python: ['def two_sum_sorted(arr, target):', '    left, right = 0, len(arr) - 1', '    while left < right:', '        s = arr[left] + arr[right]', '        if s == target: return [left, right]', '        elif s < target: left += 1', '        else: right -= 1', '    return []'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'pair<int,int> twoSumSorted(const vector<int>& arr, int target) {',
        '    int left = 0, right = arr.size() - 1;',
        '    while (left < right) {',
        '        int sum = arr[left] + arr[right];',
        '        if (sum == target) return {left, right};',
        '        if (sum < target) left++; else right--;',
        '    }',
        '    return {-1, -1};',
        '}',
        '',
        'int main() {',
        '    vector<int> arr = {1, 3, 5, 8, 12, 15, 19};',
        '    auto p = twoSumSorted(arr, 13);',
        '    cout << "Two Sum indices for target 13: " << p.first << ", " << p.second << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int[] twoSumSorted(int[] arr, int target) {', '    int left = 0, right = arr.length - 1;', '    while (left < right) {', '        int sum = arr[left] + arr[right];', '        if (sum == target) return new int[]{left, right};', '        if (sum < target) left++; else right--;', '    }', '    return new int[]{};', '}'],
      c: ['void twoSumSorted(int arr[], int n, int target) {', '    int left = 0, right = n - 1;', '    while (left < right) {', '        int sum = arr[left] + arr[right];', '        if (sum == target) { printf("Found: %d %d", left, right); return; }', '        if (sum < target) left++; else right--;', '    }', '}']
    }
  },

  containerWater: {
    id: 'containerWater',
    name: 'Container With Most Water',
    category: 'twoPointers',
    description: 'Finds two vertical lines that form container storing maximum water.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function maxArea(height) {', '  let left = 0, right = height.length - 1, maxWater = 0;', '  while (left < right) {', '    let width = right - left;', '    let h = Math.min(height[left], height[right]);', '    maxWater = Math.max(maxWater, width * h);', '    if (height[left] < height[right]) left++; else right--;', '  }', '  return maxWater;', '}'],
      python: ['def max_area(height):', '    left, right, max_water = 0, len(height) - 1, 0', '    while left < right:', '        width = right - left; h = min(height[left], height[right])', '        max_water = max(max_water, width * h)', '        if height[left] < height[right]: left += 1', '        else: right -= 1', '    return max_water'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        '#include <algorithm>',
        'using namespace std;',
        '',
        'int maxArea(const vector<int>& height) {',
        '    int left = 0, right = height.size() - 1, maxWater = 0;',
        '    while (left < right) {',
        '        int width = right - left; int h = min(height[left], height[right]);',
        '        maxWater = max(maxWater, width * h);',
        '        if (height[left] < height[right]) left++; else right--;',
        '    }',
        '    return maxWater;',
        '}',
        '',
        'int main() {',
        '    vector<int> height = {1, 8, 6, 2, 5, 4, 8, 3, 7};',
        '    cout << "Maximum Water Capacity: " << maxArea(height) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int maxArea(int[] height) {', '    int left = 0, right = height.length - 1, maxWater = 0;', '    while (left < right) {', '        int width = right - left; int h = Math.min(height[left], height[right]);', '        maxWater = Math.max(maxWater, width * h);', '        if (height[left] < height[right]) left++; else right--;', '    }', '    return maxWater;', '}'],
      c: ['int maxArea(int height[], int n) {', '    int left = 0, right = n - 1, maxWater = 0;', '    while (left < right) {', '        int width = right - left; int h = height[left] < height[right] ? height[left] : height[right];', '        int area = width * h; if (area > maxWater) maxWater = area;', '        if (height[left] < height[right]) left++; else right--;', '    }', '    return maxWater;', '}']
    }
  },

  tortoiseHare: {
    id: 'tortoiseHare',
    name: "Floyd's Tortoise & Hare Cycle Detection",
    category: 'twoPointers',
    description: 'Finds duplicate number or cycle in linked list / array using fast and slow pointers.',
    timeComplexity: { best: 'O(N)', average: 'O(N)', worst: 'O(N)' },
    spaceComplexity: 'O(1)',
    stable: true,
    code: {
      javascript: ['function findDuplicate(nums) {', '  let slow = nums[0], fast = nums[0];', '  do { slow = nums[slow]; fast = nums[nums[fast]]; } while (slow !== fast);', '  let slow2 = nums[0];', '  while (slow2 !== slow) { slow2 = nums[slow2]; slow = nums[slow]; }', '  return slow;', '}'],
      python: ['def find_duplicate(nums):', '    slow = fast = nums[0]', '    while True:', '        slow = nums[slow]; fast = nums[nums[fast]]', '        if slow == fast: break', '    slow2 = nums[0]', '    while slow2 != slow: slow2 = nums[slow2]; slow = nums[slow]', '    return slow'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int findDuplicate(const vector<int>& nums) {',
        '    int slow = nums[0], fast = nums[0];',
        '    do { slow = nums[slow]; fast = nums[nums[fast]]; } while (slow != fast);',
        '    int slow2 = nums[0];',
        '    while (slow2 != slow) { slow2 = nums[slow2]; slow = nums[slow]; }',
        '    return slow;',
        '}',
        '',
        'int main() {',
        '    vector<int> nums = {1, 3, 4, 2, 2};',
        '    cout << "Cycle Entry / Duplicate Number: " << findDuplicate(nums) << endl;',
        '    return 0;',
        '}'
      ],
      java: ['public static int findDuplicate(int[] nums) {', '    int slow = nums[0], fast = nums[0];', '    do { slow = nums[slow]; fast = nums[nums[fast]]; } while (slow !== fast);', '    int slow2 = nums[0];', '    while (slow2 !== slow) { slow2 = nums[slow2]; slow = nums[slow]; }', '    return slow;', '}'],
      c: ['int findDuplicate(int nums[], int n) {', '    int slow = nums[0], fast = nums[0];', '    do { slow = nums[slow]; fast = nums[nums[fast]]; } while (slow !== fast);', '    int slow2 = nums[0];', '    while (slow2 != slow) { slow2 = nums[slow2]; slow = nums[slow]; }', '    return slow;', '}']
    }
  },

  // --- NUMBER THEORY / MATH ---
  sieveEratosthenes: {
    id: 'sieveEratosthenes',
    name: 'Sieve of Eratosthenes',
    category: 'math',
    description: 'Finds all prime numbers up to specified integer limit N.',
    timeComplexity: { best: 'O(N log(log N))', average: 'O(N log(log N))', worst: 'O(N log(log N))' },
    spaceComplexity: 'O(N)',
    stable: true,
    code: {
      javascript: ['function sieveOfEratosthenes(n) {', '  let isPrime = Array(n + 1).fill(true);', '  isPrime[0] = isPrime[1] = false;', '  for (let p = 2; p * p <= n; p++) {', '    if (isPrime[p]) {', '      for (let i = p * p; i <= n; i += p) isPrime[i] = false;', '    }', '  }', '  return isPrime;', '}'],
      python: ['def sieve_of_eratosthenes(n):', '    is_prime = [True] * (n + 1); is_prime[0] = is_prime[1] = False', '    p = 2', '    while p * p <= n:', '        if is_prime[p]:', '            for i in range(p * p, n + 1, p): is_prime[i] = False', '        p += 1', '    return is_prime'],
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'void sieveOfEratosthenes(int n) {',
        '    vector<bool> isPrime(n + 1, true); isPrime[0] = isPrime[1] = false;',
        '    for (int p = 2; p * p <= n; p++) {',
        '        if (isPrime[p]) {',
        '            for (int i = p * p; i <= n; i += p) isPrime[i] = false;',
        '        }',
        '    }',
        '    cout << "Primes up to " << n << ": ";',
        '    for (int p = 2; p <= n; p++) if (isPrime[p]) cout << p << " ";',
        '    cout << endl;',
        '}',
        '',
        'int main() {',
        '    sieveOfEratosthenes(30);',
        '    return 0;',
        '}'
      ],
      java: ['public static void sieveOfEratosthenes(int n) {', '    boolean[] isPrime = new boolean[n + 1]; Arrays.fill(isPrime, true); isPrime[0] = isPrime[1] = false;', '    for (int p = 2; p * p <= n; p++) {', '        if (isPrime[p]) {', '            for (int i = p * p; i <= n; i += p) isPrime[i] = false;', '        }', '    }', '}'],
      c: ['void sieveOfEratosthenes(int n) {', '    bool isPrime[n + 1]; memset(isPrime, true, sizeof(isPrime)); isPrime[0] = isPrime[1] = false;', '    for (int p = 2; p * p <= n; p++) {', '        if (isPrime[p]) {', '            for (int i = p * p; i <= n; i += p) isPrime[i] = false;', '        }', '    }', '}']
    }
  }
}
